// Generated by CoffeeScript 1.6.3
(function() {
  define(["sammy", "knockout.debug"], function(Sammy, ko) {
    var SammyViewModel;
    return SammyViewModel = (function() {
      function SammyViewModel() {}

      SammyViewModel.prototype.regPatterns = function(patterns) {
        var self;
        self = this;
        return (Sammy(function() {
          var func, pattern, _results;
          _results = [];
          for (pattern in patterns) {
            func = patterns[pattern];
            _results.push(this.get(pattern, (function(func) {
              return function() {
                return func.call(self, this);
              };
            })(func)));
          }
          return _results;
        })).run();
      };

      SammyViewModel.prototype.observables = function(count) {
        var i, _i, _results;
        _results = [];
        for (i = _i = 1; 1 <= count ? _i <= count : _i >= count; i = 1 <= count ? ++_i : --_i) {
          _results.push(ko.observable());
        }
        return _results;
      };

      return SammyViewModel;

    })();
  });

}).call(this);
