// Generated by CoffeeScript 1.6.3
(function() {
  define(["sammy"], function(Sammy) {
    var SammyViewModel;
    return SammyViewModel = (function() {
      function SammyViewModel() {}

      SammyViewModel.prototype.regPatterns = function(patterns) {
        var self;
        self = this;
        return (Sammy(function() {
          var func, pattern, _results;
          _results = [];
          for (pattern in patterns) {
            func = patterns[pattern];
            _results.push(this.get(pattern, (function(func) {
              return function() {
                return func.call(self, this);
              };
            })(func)));
          }
          return _results;
        })).run();
      };

      return SammyViewModel;

    })();
  });

}).call(this);
